__version__: 1.1.0
transform:
  __class_fullname__: Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
    - __class_fullname__: InvertImg
      always_apply: false
      p: 0.5
    - __class_fullname__: Flip
      always_apply: false
      p: 0.5
    - __class_fullname__: Rotate
      always_apply: false
      border_mode: 4
      interpolation: 1
      limit:
        - -30
        - 30
      mask_value: null
      p: 0.5
      value: null
    - __class_fullname__: RandomBrightnessContrast
      always_apply: false
      brightness_by_max: true
      brightness_limit:
        - -0.2
        - 0.2
      contrast_limit:
        - -0.2
        - 0.2
      p: 0.5
    - __class_fullname__: Resize
      always_apply: true
      height: 384
      interpolation: 1
      p: 1
      width: 384
    - __class_fullname__: Normalize
      always_apply: false
      max_pixel_value: 255.0
      mean: &id001
        - 0.5
        - 0.5
        - 0.5
      p: 1.0
      std: *id001
    - __class_fullname__: ToTensorV2
      always_apply: true
      p: 1.0
      transpose_mask: false
